### ISSUE TITLE
Images stored in .gitbook not found by MkDocs

### ISSUE THREAD

**Issue by damfou** [pledra/gitbook2mkdocs#1]
I ran into the issue that images stored in the ".gitbook/assets" directory (automatically generated by Gitbook to store files) are not found to be linked in MkDocs. It does however work totally fine if that directory has any different name, say ".images" (great plugin thank you!).

The issue raised by `mkdocs serve` is:
> WARNING -  Doc file 'my-site/README.md' contains a relative link 'gbassets/my_pic.png', but the target 'my-site/gbassets/my_pic.png' is not found among documentation files.

Directory content to test it out, where "docs" is also a Gitbook space:
```
./
|_ mkdocs.yml
|_ docs
|  |_ .gitbook
|  |  |_ assets
|  |  |  |_ my_pic.png
|  |_ README.md
|  |_ SUMMARY.md
```

Content of `mkdocs.yml` is written so as to _not_ exclude the ".gitbook" directory since this is where our pictures are stored:

```yaml
site_name: my-site

nav:
  - Home: README.md
 
exclude_docs: |
  !.gitbook

plugins:
  - gitbook2mkdocs
```

Versions I used
```
mkdocs=1.5.3
gitbook2mkdocs=0.0.3
```
I tried understanding what can be the issue so I could propose a fix but it is a bit above my level...
I guess it has to be an interaction between what the `on_pre_build` & `on_post_build` methods do before & after `_set_exclusions` is called in "mkdocs/commands/build.py"?

**Comment by PCatinean** [comment]
Hi @damfou thanks a lot for the feedback, happy someone else found this plugin useful :)

I have to admit it has been a long time since I had this issue and for some reason I cannot reproduce it locally:

My mkdocs version is 1.4.2 (also upgraded to latest now) and my mkdocs,yml looks like this

```
plugins:
  - search
  - git-revision-date-localized
  - gitbook2mkdocs
  - abs-to-rel
```
I remember struggling quite a bit with this topic that mkdocs ignored the .gitbook directory and this was the reason for the symlink in serve and moving of the files with build.

Maybe if you can let me know how to reproduce this with a very simple example with installation from scratch I can probably take another look.

**Comment by damfou** [comment]
Hi @PCatinean, thanks for your reply!

I tried today to recreate my example from scratch and it works as intended, no need even for "exclude_docs" in mkdocs.yaml.

In reproducing it I realised it is my own mistake so I'd like to apologise for taking up your time!

---

For context here is what happened:

I am new to GitBook and have not longed worked with MkDocs (I am migrating away from Confluence) and for the purpose of a project I'm working on I wanted to sync a GitBook to an existing repo that has its own mkdocs already.

I wanted to be able to see my GitBook doc within MkDocs but not the opposite. I experimented with a few options all while discovering your plugin:
- syncing GitBook to /docs directly (this works and in fact does what I want),
- sync GitBook in a /docs/gitbook subdirectory: I now understand that this cannot work since your code looks for `os.path.join(config["docs_dir"], ".gitbook", "assets")` - and I believe I did not realise my setup was this one when I wrote this issue...

Sorry again and thanks for that plugin, it's really helpful!

**Comment by damfou** [comment]
As a side note: I modified your plugin into a hook to use it in conjunction with [mkdocs-monorepo-plugin](https://github.com/backstage/mkdocs-monorepo-plugin).

It's probably not perfect but I put the result here in case it is of use :)
https://github.com/damfou/gitbook2mkdocs-monorepo

Note that I somehow had to remove the .gitbook symlink for this to work.

**Comment by PCatinean** [comment]
@damfou no worries at all!

I noticed only after posting the comment that exclude_docs was there. Indeed if it had worked then it would not require the workaround I did with with the on_pre_build and post_build as it would use the original directory. But thinking about it I think I made it work somehow for mkdocs serve but the mkdocs build failed to identify it so that's why I remained with this approach.

Probably there's an easier way but I didn't figure it out ;)
